# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Ambiente para desplegar'
        # Default value if no value is explicitly provided
        default: 'staging'
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options: 
          - staging
          - qa

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
<<<<<<< HEAD
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
         with:
          browser: chrome
=======
  # This workflow contains a single job called "greet"
 cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      -uses: actions/checkout@v2.5.0
      -name: Use Node.js ${{ matrix-node-version}}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix-node-version}}
      -name: Cypress run
       uses: cypress-io/github-action@v4
       with:
        record: false
