# This is a basic workflow that is manually triggered

name: Cypress run test suite

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Ambiente para desplegar'
        # Default value if no value is explicitly provided
        required: true
        type: choice
        options: 
          - staging
          - qa

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    name: Cypress run
    strategy:
      matrix:
        version: [16]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
         with:
          browser: chrome
